Vagrant.configure("2") do |config|
  # Forcer VirtualBox comme provider
  config.vm.provider "virtualbox"

  # Machine Client
  config.vm.define "client" do |client|
    client.vm.box = "debian/bookworm64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.20"

    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    client.vm.synced_folder "./scripts", "/home/vagrant/scripts"

    client.vm.provision "shell", inline: <<-SHELL
      echo "Installation du client..."
      sudo apt update
      sudo apt install -y curl nmap
      echo "Client prêt avec curl et nmap !"
    SHELL
  end
end
