Vagrant.configure("2") do |config|
  # Forcer VirtualBox comme provider
  config.vm.provider "virtualbox"

  # Machine Serveur
  config.vm.define "server" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    server.vm.synced_folder "./scripts", "/home/vagrant/scripts", create: true

    server.vm.provision "shell", inline: <<-SHELL
      echo "Installation du serveur..."
      sudo apt update
      sudo apt install -y nginx ufw
      sudo systemctl start nginx
      echo "Serveur prêt avec Nginx et UFW !"
    SHELL
  end
end
