Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "server"
  config.vm.network "private_network", ip: "192.168.0.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y nginx ufw
    sudo ufw allow 80
    sudo ufw allow 443
    sudo ufw enable
    sudo systemctl start nginx
  SHELL
end

